version: "3.3"

services:
  api:
    # image: gpstrange/node-tutorial-app:1.5
    build: .
    ports:
      - "8082:8080"
    command: npm start
    environment:
      DB_URL: mongodb://mongo:27017
      PORT: 8080
      SENSOR_HOST: host.docker.internal
    # depends_on: 
    #   - mongo
    extra_hosts:
    - "host.docker.internal:host-gateway"

  mongo:
    image: mongo:4
    ports:
      - "27018:27017"

  request-generator:
    image: gpstrange/node-tutorial-trace-gen:1.5
    command: npm start
    environment:
      SERVER_URL: http://api:8080
    depends_on: 
      - api