apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-tutorial-app
spec:
  selector:
    matchLabels:
      app: node-tutorial-app
  template:
    metadata:
      labels:
        app: node-tutorial-app
    spec:
      containers:
      - name: node-tutorial-app
        image: gpstrange/node-tutorial-app:1.2
        imagePullPolicy: Always
        env:
        - name: KUBESENSE_POD_IP 
          valueFrom:
            fieldRef:
              apiVersion: v1 
              fieldPath: status.podIP
        - name: DB_URL
          value: mongodb+srv://guruprasad:MXCWck99D4dzWbVx@cluster0.ojk1a.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        - name: OTEL_SERVICE_NAME
          value: node-tutorial-app-otel
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://my-otel-demo-otelcol.otel-demo.svc.cluster.local:4318
        - name: OTEL_RESOURCE_ATTRIBUTES 
          value: "kubesense.env_type=k8s,kubesense.ip=$(KUBESENSE_POD_IP)"
---
apiVersion: v1
kind: Service
metadata:
  name: node-tutorial-app
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      name: node-tutorial-app